version: '3.7'

services:
  entropy-app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9394:9394"
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/entropy?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: entropy
      SPRING_DATASOURCE_PASSWORD: silencer&&55
    networks:
      - backend

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: entropy
      MYSQL_USER: entropy
      MYSQL_PASSWORD: silencer&&55
      MYSQL_ROOT_PASSWORD: silencer&&55
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend: