version: '3.3'

services:

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: entropyb
      MYSQL_USER: entropy
      MYSQL_PASSWORD: Silencer&&55
      MYSQL_ROOT_PASSWORD: Silencer&&55
    volumes:
      - db-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - entropy-backend-network

  entropy-app-server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/entropyb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: entropy
      SPRING_DATASOURCE_PASSWORD: Silencer&&55
    networks:
      - entropy-backend-network

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  entropy-backend-network: