#Config app
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entropyb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Silencer&&55

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: dc5f322981574f18b6aa
            client-secret: 5cffe0d9fcec3c4244df39a10ff7e8f62b7a6532
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

          facebook:
            client-id: 813313625494017
            client-secret: 04bf09893e23dcd359e534e3ff409bb1
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v3.0/dialog/oauth
            token-uri: https://graph.facebook.com/v3.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    enabled: true
    schemas: entropyb
    locations: classpath:db/migration

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /api
  port: 1109

app:
  auth:
    token-secret: ZGltYWdlc2hhcmUtbGVnYWN5LWJhY2tlbmQtcHJvamVjdA==
    token-expiration-msec: 36000000

  oauth2:
    auth-request-cookie-name: oauth2_auth_request
    redirect-uri-param-cookie-name: redirect_uri
    cookie-expire-seconds: 120
    authorized-redirect-uris:
      http://localhost:3000/oauth2/redirect,
      myandroidapp://oauth2/redirect,
      myiosapp://oauth2/redirect

  file:
    upload-dir: /tmp/entropyb