#Config app
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entropyb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Silencer&&55

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: dc5f322981574f18b6aa
            client-secret: 5cffe0d9fcec3c4244df39a10ff7e8f62b7a6532
  flyway:
    baseline-on-migrate: true
server:
  servlet:
    context-path: /api

app:
  auth:
    tokenSecret: ZGltYWdlc2hhcmUtbGVnYWN5LWJhY2tlbmQtcHJvamVjdA==
    tokenExpirationMsec: 360000

  file:
    upload-dir: /tmp/entropyb